
export const AUTH_IS_LOADING = 'AUTH_IS_LOADING';
export const AUTH_IS_SUCCEED = 'AUTH_IS_SUCCEED';
export const AUTH_IS_FAILED = 'AUTH_IS_FAILED';

export const SUBSCRIBE_IS_LOADING = 'SUBSCRIBE_IS_LOADING';
export const SUBSCRIBE_IS_SUCCEED = 'SUBSCRIBE_IS_SUCCEED';
export const SUBSCRIBE_IS_FAILED = 'SUBSCRIBE_IS_FAILED';

export const RECOVERY_BY_PHONE_IS_LOADING = 'RECOVERY_BY_PHONE_IS_LOADING';
export const RECOVERY_BY_PHONE_IS_SUCCEED = 'RECOVERY_BY_PHONE_IS_SUCCEED';
export const RECOVERY_BY_PHONE_IS_FAILED = 'RECOVERY_BY_PHONE_IS_FAILED';

export const RECOVERY_BY_LOGIN_IS_LOADING = 'RECOVERY_BY_LOGIN_IS_LOADING';
export const RECOVERY_BY_LOGIN_IS_SUCCEED = 'RECOVERY_BY_LOGIN_IS_SUCCEED';
export const RECOVERY_BY_LOGIN_IS_FAILED = 'RECOVERY_BY_LOGIN_IS_FAILED';



